# -*- coding: utf-8 -*-
"""Data Storage Microservice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AvPfFvyAfhhtwKAxmfY6-2BlB379zOlJ
"""

import os
import json
import boto3

from flask import Flask, request, jsonify

app = Flask(__name__)

# AWS DynamoDB configuration
DYNAMODB_REGION = 'your-dynamodb-region'
DYNAMODB_TABLE_NAME = 'your-dynamodb-table-name'

# Route to store the processed GitHub data in DynamoDB
@app.route('/store-processed-data', methods=['POST'])
def store_processed_data():
    data = request.json
    repo = data.get('repository')
    processed_data = data.get('processed_data')

    if not repo or not processed_data:
        return jsonify({"error": "Invalid request. Please provide 'repository' and 'processed_data' in the request body."}), 400

    # Store processed data in DynamoDB
    store_data_in_dynamodb(repo, processed_data)

    return jsonify({"message": "Processed data stored successfully in DynamoDB."})

# Function to securely store processed data in DynamoDB
def store_data_in_dynamodb(repo, processed_data):
    try:
        # Initialize DynamoDB client using IAM role credentials
        session = boto3.Session()
        dynamodb = session.resource('dynamodb', region_name=DYNAMODB_REGION)
        table = dynamodb.Table(DYNAMODB_TABLE_NAME)

        # Example: Store data with a unique identifier as the partition key
        unique_id = f'{repo}-processed-data'
        table.put_item(Item={unique_id: processed_data})

        print("Data stored in DynamoDB successfully.")
    except Exception as e:
        print(f"Error storing data in DynamoDB: {str(e)}")

if __name__ == '__main__':
    app.run(port=5003)