apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-storage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-storage
  template:
    metadata:
      labels:
        app: data-storage
    spec:
      containers:
      - name: data-storage
        image: tharushisamara/data-storage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: data-storage-service
spec:
  selector:
    app: data-storage
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5003
  type: NodePort
