apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-data-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-data-collector
  template:
    metadata:
      labels:
        app: github-data-collector
    spec:
      containers:
      - name: github-data-collector
        image: tharushisamara/github-data-collector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: github-data-collector-service
spec:
  selector:
    app: github-data-collector
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: NodePort

