name: Data Processor CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start minikube
      uses: medyagh/setup-minikube@master	

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build -t tharushisamara/data-processor:latest --file ./Data_Processor/Dockerfile --platform linux/amd64,linux/arm64 --push .

    - name: Deploy to Minikube on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull tharushisamara/data-processor:latest

    - name: Copy deployemnt file to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./K8s/data_processor_deployment.yml"
        target: "/home/${{ secrets.EC2_USERNAME }}/"

    - name: Start minikube
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./K8s/data_processor_deployment.yml"
        script: minikube start	
    
    - name: Deploy to Minikube
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
            kubectl apply -f ./K8s/data_processor_deployment.yml    
            kubectl get pods
    
            kubectl wait --for=condition=available --timeout=150s deployment/data-processor 
        
    - name: Getting Minikube IP
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
            minikube ip
            kubectl get service data-processor-service  -o=jsonpath='{.spec.ports[0].nodePort}'
    
    - name: Expose deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: 
            kubectl get pods
            kubectl expose deployment data-processor --type=NodePort --port=5000
    
    - name: Expose Minikube service externally (for demo purposes)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
            minikube service data-processor-service --url
