name: Data_Storage CI/CD

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        sudo dpkg -i minikube_latest_amd64.deb
        sudo apt-get install -y conntrack
        sudo minikube start --driver=docker

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker CLI
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        server-url: https://index.docker.io/v1/

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build -t tharushisamara/data-storage:latest --platform linux/amd64,linux/arm64 -o type=registry .
        docker push tharushisamara/data-storage:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f K8s/data_storage_deployment.yml
        # kubectl apply -f data_storage/service.yml

        # Wait for the deployment to complete
        kubectl wait --for=condition=available --timeout=300s deployment/data-storage

    - name: Set up DynamoDB Table
      run: |
        # Add steps to set up DynamoDB table, e.g., using AWS CLI
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
        aws dynamodb create-table --table-name Developer-Tracking-Data --attribute-definitions AttributeName=owner,AttributeType=S AttributeName=repo,AttributeType=S --key-schema AttributeName=owner,KeyType=HASH AttributeName=repo,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

        # Wait for DynamoDB table creation to complete
        aws dynamodb wait table-exists --table-name Developer-Tracking-Data

    - name: Expose Minikube service externally (for demo purposes)
      run: |
        sudo minikube service data-storage --url
