name: Data Processor CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Build Docker image
      run: docker build -t tharushisamara/data-processor:latest .

    - name: Push Docker image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push tharushisamara/data-processor:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        sudo dpkg -i minikube_latest_amd64.deb
        sudo apt-get install -y conntrack
        sudo minikube start --driver=docker

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        install-kubectl: true

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/deployment.yml
        kubectl apply -f kubernetes/service.yml

        # Wait for the deployment to complete
        kubectl wait --for=condition=available --timeout=300s deployment/data-processor

        # Print Minikube IP and port for verification
        minikube ip
        kubectl get service data-processor-service -o=jsonpath='{.spec.ports[0].nodePort}'

        # Add any additional verification or testing steps

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
