name: GitHub_Data_Collector CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build -t tharushisamara/github-data-collector:latest --file ./GitHub_Data_Collector/Dockerfile --platform linux/amd64,linux/arm64 --push .
    
    - name: Connect with EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull tharushisamara/github-data-collector:latest

    - name: Copy deployemnt file to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./K8s/github_data_collector_deployment.yml"
        target: "/home/${{ secrets.EC2_USERNAME }}/"
    
    - name: Start minikube
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          minikube start

    - name: Delete Kubernetes Service if exists
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          kubectl delete -f ./K8s/github_data_collector_deployment.yml || true

          kubectl wait --for=delete service/github-data-collector --timeout=300s --ignore-not-found || echo "Service not found or deletion completed"


    - name: Deploy to Minikube
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          kubectl apply -f ./K8s/github_data_collector_deployment.yml    
          kubectl get pods

          kubectl wait --for=condition=available --timeout=150s deployment/github-data-collector 
      # run: |
      #     whoami
        # kubectl apply -f ./K8s/github_data_collector_deployment.yml    
        # kubectl get pods

        # kubectl wait --for=condition=available --timeout=150s deployment/github-data-collector 
    - name: Getting Minikube IP
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          minikube ip
          kubectl get service github-data-collector-service  -o=jsonpath='{.spec.ports[0].nodePort}' 

    - name: Delete Kubernetes Service if exists
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          kubectl delete service github-data-collector --ignore-not-found
          
    - name: Expose deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          kubectl get pods
          kubectl expose deployment github-data-collector --type=LoadBalancer --port=8080

    - name: Expose Minikube service externally (for demo purposes)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          minikube service github-data-collector-service --url
          kubectl get svc

    - name: Expose Minikube service externally (for demo purposes)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: minikube tunnel

          
