name: GitHub_Data_Collector CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        sudo dpkg -i minikube_latest_amd64.deb
        sudo apt-get install -y conntrack
        sudo minikube start --driver=docker

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker CLI
      uses: docker/login-action@v1
      with:
        image: tharushisamara/developer-test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        server-url: https://docker.io/v1/

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build -t your-docker-hub-username/github-data-collector:latest --platform linux/amd64,linux/arm64 -o type=registry .
        docker push your-docker-hub-username/github-data-collector:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f github_data_collector/deployment.yml
        kubectl apply -f github_data_collector/service.yml

        # Wait for the external IP to be assigned
        kubectl wait --for=condition=available --timeout=300s deployment/github-data-collector
        minikube service github-data-collector --url

    - name: Expose Minikube service externally (for demo purposes)
      run: |
        sudo minikube service github-data-collector --url
