name: GitHub_Data_Collector CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Create non-root user and switch
      run: |
        sudo useradd -m github-runner
        sudo runuser -l github-runner -c 'minikube start --driver=docker'

    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        sudo dpkg -i minikube_latest_amd64.deb
        sudo apt-get install -y conntrack
        sudo minikube start --driver=docker
        minikube status

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker buildx create --use
        docker buildx build -t tharushisamara/github-data-collector:latest --platform linux/amd64,linux/arm64 --push .
        
    - name: Deploy to Minikube
      run: |
        kubectl apply -f K8s/github_data_collector_deployment.yml
        kubectl wait --for=condition=available --timeout=300s deployment/github-data-collector
        minikube service github-data-collector --url

    - name: Expose Minikube service externally (for demo purposes)
      run: |
        sudo minikube service github-data-collector --url